### ISSUE TITLE
Can't Open

### ISSUE THREAD

**Issue by ghost** [mao2116/mbomb#1]
Non-UTF-8 code starting with '\xfb' in file /home/ghostv33/Downloads/mbomb-main/MBOMB on line 4, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

Showing this error when opening on linux

**Comment by mao2116** [comment]
You Can use Tbomb_mao For batter experience. 
Here Link: https://github.com/mao2116/tbomb_mao

**Comment by ghost** [comment]
> You Can use Tbomb_mao For batter experience. Here Link: https://github.com/mao2116/tbomb_mao

thanks this is working

**Comment by mao2116** [comment]
Yeap!🥰😇
